yolo_model:

  config_file:
    name: yolotiny-colour.cfg
  weight_file:
    name: colour_detect.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - green
      - red
      - dark